metrumresearchgroup/pkgr

Makefile
cmd/install.go
cmd/plan.go
cmd/utils.go
gpsr/dependencies.go
gpsr/solution.go
gpsr/structs.go
integration_tests/mixed-source/pkgr.yml

This could be done a little cleaner, but I wanted to throw this basic idea out there.
This was a potential refactoring I thought of when looking into #75 . My instincts tell me doing this will be helpful for differentiating between dependencies and user-level packages in the logs, but I haven't quite connected the dots yet.

change: refactored InstallPlan to carry its own download information.

---

configlib/config.go

turns out the code was already there, it was just buried under a small logic error.
references #126

add: error message indicating when config file could not be found.

---

cmd/root.go
cran/download-package.go
cran/repodb.go
cran/utils.go

osx 4.0 cran now drops el-capitan part of path
closes: #264

fix: osx R 4.0 url

---

cmd/root.go
rcmd/install.go

prior to fix, given a package with a respository field that was a superset of the repository in the pkgr.yml, it would not replace.
For example, PKPDmisc has `Repository: MPNDEV` in the source tarball so when installing from MPN the existing strings.Contains would still match true to `Repository: MPN` and not replace
```
Version: 1
Packages:
- PKPDmisc
Repos:
- MPN: https://mpn.metworx.com/snapshots/stable/2020-08-15/
Lockfile:
Type: renv
```
```
Package: PKPDmisc
Type: Package
Title: Pharmacokinetic and Pharmacodynamic Data Management Functions
Version: 3.0.0
Date: 2020-06-25
Authors@R: c(
person("Devin", "Pastoor",
email = "devin.pastoor@gmail.com", role = c("aut", "cre")))
Description: A toolbox for data management common to pharmacokinetic and
pharmacokinetic modeling and simulation, …
```

fix repository matching

---

cmd/root.go
configlib/config.go

closes #319 
The two likely candidates for existing CI use by users are library and rpath. In general this should not impact people but is a breaking change to the user api, thus bumping the major version.

feat: simplify autoenv behavior

---

cmd/install.go
cmd/plan.go
configlib/structs.go

this will currently rip them out of the dep tree, so an ignored package
and all its deps will be removed. This means if that package is part of
the required package set it will cause the solve to fail, however
when having some suggested deps that want to selectively exclude
can work well.

exp: allow for ignoring certain packages in the solve

---

cmd/install_test.go
cmd/pkgr/goreleaser.yml
cmd/plan.go
cmd/root.go
cmd/run.go
configlib/config.go
configlib/config_test.go
configlib/get_customization.go
configlib/get_customization_test.go
configlib/structs.go

One of the more subtle bugs that has emerged is due to the fact that viper is a bit loose around how it unmarshals, when combined with some interface{} related flexible code meant that when needing a structure that actually mapped to the actual expected config more explicitly, some failures occured.
In particular, with the add/remove commands, explicit yaml unmarshalling vs viper was used and was getting parsing errors in the yaml. This actually showed that the exisitng underlying struct vs the user specification was off. This has now been fixed, but also showed where a different underlying structure has been used throughout the code.
Namely, as a user customizations are specified as arrays:
```
Packages:
- dplyr:
Suggests: true
- ggplot2:
Repo: something
```
This structure is a slice of …

fix customization code

---

cmd/install.go
cmd/plan.go
integration_tests/simple/pkgr.yml
rcmd/install.go
rcmd/structs.go

This PR provides a combined output structure instead of separated stdout and stderror streams (though we also retained the separated version internally and for trace level output.
This was a pain point for diagnosing as during installation many pieces swap back and forth printing to stdout or stderr so trying to actually read a linear set of messages to understand how the install proceeded was basically impossible. This is especially so for packages with c++ code that the compilation output gets emitted

combined install output

---

.drone.yml
Makefile
cmd/pkgr/goreleaser.yml
cmd/pkgr/pkgr.go
cmd/root.go
go.sum
integration_tests/baseline/Makefile
integration_tests/integration_helper/runt.go
integration_tests/version/.gitignore
integration_tests/version/Makefile
integration_tests/version/guide.md
integration_tests/version/version_test.go

This PR adds `--version` and `-v` flags
```
pkgr --version
pkgr -v
```
which will return the injected build tag for any published release - eg. v3.0.1

add version flags

---

cran/download-package.go

There is what appears to be an extra space in the log message for "downloading package".  If it's intentional, no worries about closing this.

remove extra space in log message

---

go.mod
go.sum

brotli v1.0.1 has been retracted:
$ make
cd cmd/pkgr; go get; go install
go: warning: github.com/andybalholm/brotli@v1.0.1: retracted by
module author: occasional panics and data corruption
go: to switch to the latest unretracted version, run:
go get github.com/andybalholm/brotli@latest
Run the suggested `go get` command followed by `go mod tidy`.

dep: update retracted brotli version to latest version

---

NEWS.md

This PR adds a NEWS.md file with
* Seth's [release notes for v3.0.0](https://github.com/metrumresearchgroup/pkgr/releases/tag/v3.0.0)
* release notes for the next release, v3.1.0
I think keeping these release notes in the repo is a good idea given the plan is to prepare them for releases anyway, but I don't have strong preferences on the name of the file or other specifics.
changeset: https://github.com/metrumresearchgroup/pkgr/compare/bccaa523f7df3cd64e0534a0607953da96ddaa4b...e24ccac52d5313b3c715604e6f01e90c70463c5b

Prepare v3.1.0 release

---

NEWS.md

I had a stale tag locally.  This made it into the 3.0.0 tag that's now
on GitHub.

NEWS.md: move GOMAXPROCS item to 3.0.0

---

configlib/config.go
integration_tests/bad-customization/bad_customization_test.go
integration_tests/bad-customization/pkgr.yml
integration_tests/library/libraries_test.go

The last commit of fixes renv detection when other code startup code writes to stdout.  I hit into a case in the wild where someone's .Rprofile `cat` some text, leading to `pkgr` aborting because it received more than one line on stdout.  (Cases that use `message` don't hit into this because that writes to stderr.)
Demo:
```
$ head -1 .Rprofile
cat("bah\n")
$ pkgr plan
WARN[0000] expected one line for renv library, got 2:
["bah" "/data/home/kylem/src/github/metrumresearchgroup/nmrec/renv/library/R-4.1/x86_64-pc-linux-gnu"]
FATA[0000] Lockfile type is renv, but calling renv to find library path failed.
Check that renv is installed or consider using `Library:` instead.
```
The first two patches clean up an unrelated test failure that I noticed when pushing this branch.  It looks like it's …

config: mark renv library path for more reliable detection

---

README.md

Both the macOS and Linux installation sections repeat information that is already on the release page.  The Linux instructions are version-specific, so the README needs to be updated every release to stay up to date.
Avoid duplicating the instructions and instead just point to the latest release page.

README: reduce Linux/macOS install instructions to pointer

---

.drone.yml
configlib/config_test.go
configlib/testsite/integration_test_archive/customization/pkgr.yml
configlib/testsite/integration_test_archive/repo-order/pkgr.yml
configlib/testsite/integration_test_archive/simple-suggests/pkgr.yml
configlib/testsite/integration_test_archive/simple/pkgr.yml
configlib/testsite/many-settings/pkgr.yml
configlib/testsite/packrat-library/pkgr.yml
configlib/testsite/renv-library/pkgr.yml
configlib/testsite/simple/pkgr.yml
cran/pkg_nexus_test.go
cran/utils_test.go
gpsr/helpers_test.go

<https://cran.microsoft.com/> has been shut down.  Although `cran.microsoft.com` URLs occur in a good number of files, there are actually only a few places that actually try to connect.  The second and third commit of this series fixes those, and the fourth commit updates the Drone configuration so that those tests are executed.
The final commit removes some more `cran.microsoft.com` URLs, but, unlike the ones in the earlier commits, these updates aren't actually necessary because the tests don't connect.  That commit message also has an overview of the remaining occurrences of `cran.microsoft.com` URLs, all of which I think are fine to leave be at this point.
Closes #409.

tests: update for MRAN retirement

---

NEWS.md

The only user-facing change is the renv detection fix from gh-408.
changeset: https://github.com/metrumresearchgroup/pkgr/compare/273972eb7decbabddd7875ee7095e61661f12884...092c8f5a3f7f494af5934882f62005bf7d0dd386

Prepare 3.1.1 release

---

cmd/descriptionOps_test.go
cmd/remove.go
docs/validation/matrix.yaml
integration_tests/addremove/addremove_test.go
scripts/run-integration-tests

This PR adds tests for the zero-coverage files that remain in the per file report after gh-420.  The tip commit fixes a code typo of no functional consequence.
Here's the per file coverage table generated with a scratch merge of this PR and gh-420.
<details>
<summary>table</summary>
```
$ git rev-parse f2bfecc^{tree}
50a826a7257484d1498dd1e5f3b31b6cb54d6662
$ jq -r '.files | .[] | [.file, .coverage] | @tsv' \
<internal/valtools/output/pkgr_3.1.1-59-gf2bfecc/pkgr_3.1.1-59-gf2bfecc.coverage.json | \
sort -k2 -g | awk '{printf "%s\t%.2f\n", $1,$2}' | column -t
testhelper/e2e_tests.go         1.69
cmd/debug.go                    9.09
cmd/run.go                      22.22
cmd/experiment.go               25.00
logger/logger.go                31.43
gpsr/install.go                 50.00 …
```

Add a few tests

---

.github/workflows/main.yaml
cmd/pkgr/goreleaser.yml

The goreleaser action requires version 2 of the config format.

Update goreleaser configuration

---

go.mod
go.sum

https://github.com/metrumresearchgroup/pkgr/security/dependabot/12 flagged a memory leak in the ulikunitz/xz package.  This doesn't look relevant for pkgr (see commit message for details), so the main purpose of this update is to quiet security scanners.
ulikunitz/xz 0.5.14 addressed the memory leak and was quickly followed by a 0.5.15 release to resolve an issue with the 0.5.14 fix.
---
This PR replaces dependabot's gh-429, which updates to 0.5.14 rather than 0.5.15.

go.mod: update ulikunitz/xz to fix security warning
